---
title: House of Worship Ministries
timezone: UTC

include: ["_posts"]

collections:
  events:
    title: Events
    output: true
    permalink: "/events/:path"
  pages:
    title: Main Pages
    output: true
    permalink: "/:path"
  posts:
    output: true
  uploads:
    title: Uploads
    output: true
email: tuhilary@gmail.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: //www.houseofworshipministries.co.za
markdown: kramdown
theme: minima
plugins: 
include:
- _pages
permalink: pretty
sass:
  sass_dir: _sass
  style: compressed
  sourcemap: true

future: true