---
title: House of Worship Ministries
timezone: UTC
collections:
  events:
    title: Events
    output: true
    permalink: "/events/:path"
  pages:
    title: Main Pages
    output: true
    permalink: "/:path"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: tuhilary@gmail.com
description: 
baseurl: ''
url: http://www.houseofworshipministries.co.za
markdown: kramdown
theme: minima
plugins: 
include:
- _pages
permalink: pretty
sass:
  sass_dir: _sass
  style: compressed
  sourcemap: true
