hero:
  description: asdasd
  jumbotron: img/Cross.jpg
  title: Servicesssssss
intro:
  body: Body text
  header: Welcome
services:
  content: >-
    Sunday Service:<br/>Sundays from 10:00AM - 1:00PM<br/><br/>Prayer
    Warriors:<br/>Mondays from 6:00PM - 7:30PM<br/><br/>Bible
    Study:<br/>Tuesdays from 6:00PM - 7:30PM<br/><br/>Mid-Week
    Service:<br/>Wednesdays from 6:00PM - 7:30PM<br/><br/>Prayer
    Meeting:<br/>Fridays from 6:00PM - 7:30PM
  heading: Church Weekly Programs
  image: img/Cross.jpg
