---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: ''
  label: Events
  create: all
  match: _events/*
  templates:
  - default
- type: directory
  path: ''
  label: Main Pages
  create: all
  match: _pages/*
  templates:
  - default
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
upload_dir: img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
