backend:
  name: github
  branch: master
  repo: riyaadh47/hilary
  app_id: b9d5ff96-efb3-427f-a446-ca17f0152bf4
  client_id: ccb89011e2942e8dd158


collections:
  - label: "Homepage"
    name: "homepage"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "_data/homepage.yml"
        fields:
          - label: "Banner"
            name: "call-to-action"
            widget: "object"
            fields:
              - label: "Heading"
                name: "paragraph"
                widget: "markdown"
              - label: "Title"
                name: "heading"
                widget: "markdown"
              - label: "Slider"
                name: "slider"
                widget: "list"
                fields:
                  - label: "Slider Image"
                    name: "img"
                    widget: "image"




media_folder: "/images/"
public_folder: "/images/uploads"