backend:
  name: github
  branch: master
  repo: riyaadh47/hilary
  app_id: b9d5ff96-efb3-427f-a446-ca17f0152bf4
  client_id: ccb89011e2942e8dd158


collections:
  - label: "Homepage"
    name: "homepage"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "_data/homepage.yml"
        fields:
          - label: "Banner"
            name: "call-to-action"
            widget: "object"
            fields:
              - label: "Heading"
                name: "paragraph"
                widget: "markdown"
              - label: "Title"
                name: "heading"
                widget: "markdown"
              - label: "Slider"
                name: "slider"
                widget: "list"
                fields:
                  - label: "Slider Image"
                    name: "img"
                    widget: "image"
          - label: "Content Block"
            name: "contentBlock"
            widget: "object"
            fields:
              - label: "Heading"
                name: "heading"
                widget: "string"
              - label: "Bible Verse"
                name: "bibleVerse"
                widget: "string"
          - label: "Scriptures"
            name: "scriptures"
            widget: "list"
            fields:
              - label: "Image"
                name: "hero"
                widget: "image"
              - label: "Title"
                name: "heading"
                widget: "string"
              - label: "Content"
                name: "paragraph"
                widget: "markdown"


  - label: "Events"
    name: "events"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Debate", name: "debate", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Church", name: "church", widget: "string"}
      - {label: "Jumbotron (Banner)", name: "jumbotron", widget: "image"}
      - {label: "Event image", name: "image", widget: "image"}
      - {label: "Content", name: "body", widget: "markdown"}





media_folder: "/img/"
public_folder: "/img/"