backend:
  name: github
  branch: master
  repo: riyaadh47/hilary
  app_id: b9d5ff96-efb3-427f-a446-ca17f0152bf4
  client_id: ccb89011e2942e8dd158


collections:
  
  - label: "Homepage"
    name: "homepage"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "_data/homepage.yml"
        fields:
          - label: "Banner"
            name: "call-to-action"
            widget: "object"
            fields:
              - {label: "Heading", name: "paragraph", widget: "markdown"}
              - {label: "Title", name: "heading", widget: "markdown"}
              - label: "Slider"
                name: "slider"
                widget: "list"
                fields:
                  - label: "Slider Image"
                    name: "img"
                    widget: "image"
          - label: "Content Block"
            name: "contentBlock"
            widget: "object"
            fields:
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Bible Verse", name: "bibleVerse", widget: "string"}
          - label: "Scriptures"
            name: "scriptures"
            widget: "list"
            fields:
              - {label: "Image", name: "hero", widget: "image"}
              - {label: "Title", name: "heading", widget: "string"}
              - {label: "Content", name: "paragraph", widget: "markdown"}

          - label: "Pre Footer"
            name: "pre-footer"
            widget: "object"
            fields:
              - {label: "Background Image", name: "backgroundImage", widget: "image"}
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Paragraph", name: "paragraph", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}
              - {label: "Link name", name: "linkName", widget: "string"}

  - label: "About"
    name: "name"
    files:
      - label: "About"
        name: "about"
        file: "_data/about.yml"
        fields:
          - label: "Hero"
            name: "hero"
            widget: "object"
            file: "_pages/about-us.html"
            fields:
              - label: "Jumbotron"
                name: "jumbotron"
                widget: "image"
              - label: "Description"
                name: "description"
                widget: "markdown"
          - label: "About"
            name: "about"
            allow_add: false
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Snippet"
                name: "snippet"
                widget: "string"
          - label: "Pastors"
            name: "pastors"
            widget: "list"
            allow_add: true
            fields:
              - label: "Pastor name"
                name: "name"
                widget: "string"
              - label: "Pastor Surname"
                name: "surname"
                widget: "string"
              - label: "About Pastor"
                name: "about"
                widget: "markdown"
              - label: "Excerpt"
                name: "excerpt"
                widget: "string"
              - label: "Pastor Picture"
                name: "picture"
                widget: "image"


  - label: "Events"
    name: "events"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Debate", name: "debate", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Church", name: "church", widget: "string"}
      - {label: "Jumbotron (Banner)", name: "jumbotron", widget: "image"}
      - {label: "Event image", name: "image", widget: "image"}
      - {label: "Content", name: "body", widget: "markdown"}


  - label: "Gallery"
    name: "gallery"
    files:
      - label: "Gallery"
        name: "gallery"
        file: "_data/gallery.yml"
        fields:
          - label: "Gallery Images"
            name: "gallery"
            widget: "list"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Thumbnail"
                name: "thumb"
                widget: "image"
              - label: "Title"
                name: "title"
                widget: "string"
  
  - label: "Services"
    name: "services"
    files:

      - label: "Services"
        name: "services"
        file: "_data/services.yml"
        fields:

          - label: "Hero"
            name: "hero"
            widget: "object"
            file: "_pages/services.html"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown"}
              - {label: "Image", name: "jumbotron", widget: "image"}
          
          - label: "Intro"
            name: "intro"
            widget: "object"
            fields:
              - {label: "Intro Header", name: "header", widget: "string"}
              - {label: "Intro Body", name: "body", widget: "markdown"}
          
          - label: "Church Weekly Programs"
            name: "services"
            widget: "object"
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Content", name: "content", widget: "markdown"}



media_folder: "/img/"
public_folder: "/img/"