---
label: default
hide_body: false
is_partial: false
fields:
- type: select
  name: layout
  config:
    source:
      type: simple
    options:
    - default
    - page
  label: layout
- type: text
  name: title
  label: title
- type: number
  name: order
  label: Order
pages:
- _pages/another-page.md
- index.html
- _pages/donate.md
- _pages/services.md
