---
label: default
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: layout
  label: layout
  default: default
pages:
- _pages/b.md
- _pages/events.md
- 1st-event.md
