---
label: default
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: layout
  label: layout
  default: default
- type: number
  name: order
  label: Order
pages:
- _pages/events.md
- _pages/services.md
