---
label: default
hide_body: false
is_partial: false
fields:
- type: select
  name: layout
  config:
    source:
      type: simple
    options:
    - default
    - page
  label: layout
- type: text
  name: short-date
  label: Short Date
- type: text
  name: event-date
  label: Full Date
- type: text
  label: debate
  name: debate
- type: text
  name: title
  label: title
- type: number
  name: order
  label: Order
- type: text
  label: Description
  name: description
- type: file
  name: jumbotron
  label: Jumbotron
pages:
- index.html
- _pages/contact.html
- _pages/events.html
- _pages/donate.html
- _pages/services.html
- _pages/about-us.html
