---
label: default
hide_body: false
is_partial: false
fields:
- type: select
  name: layout
  config:
    source:
      type: simple
    options:
    - default
    - page
  label: layout
- type: text
  name: title
  label: title
- type: number
  name: order
  label: Order
- type: text
  label: Description
  name: description
- type: file
  name: jumbotron
  label: Jumbotron
pages:
- _pages/page-3.html
- _pages/page-2.html
- _pages/page-1.html
- _pages/testing-123.html
- index.html
